export const lyrics = [
  "Mm",
  "Feels so good",
  "Pussy blow me away",
  "Mm, blow me away",

  `"The way you kiss me when I'm strokin' deep inside of it"`,
  `I swear you ride it so good (So good)`,
  `That pussy blow me away`,
  `And I been thinkin' 'bout your smile`,
  `All mornin' for a while`,
  `'Bout the way you twist your face while I'm strokin' in and out`,
  `Girl, you shocked me, I'm so wowed`,
  `Got me slippin', I'm like, "How?"`,
  "First I met you on the 'Gram, I picked you up and took you out",
  `Let me show you what I'm 'bout`,
  "Let them haters run they mouth",
  `You should know you somethin' different 'cause I brought you to my house`,
  "Serve you breakfast on my couch",
  `Anything you ever need, you know I'll be there with no doubt`,
  `I need you by my side, I hope you're here to ride`,
  "I hate to see you hurtin', my lil' baby, wipe your eyes",
  "Baby, let me pull your dress down (Dress down)",
  "Kiss you from your neck down (Neck down)",
  `Have you screaming "Oh"`,
  "Baby, just let me pull your dress down",
  "Kiss you from your neck down",
  `Have you screaming "Oh," them sex sounds`,

  `Baby, I need you in my life, it's like there's no one there`,
  `Nobody, can I turn to you next time there's no one there?`,
  `I need a girl to match my loyalty when times get rough`,
  `I turn to you 'cause I know damn well you don't give a fuck`,
  `About them, let them niggas hate`,
  `Either way, regardless what they saying, we'll be great`,
  `Let's go explore the whole world, fuck the skippin' states`,
  `You got me feelin' different, I might let it go today`,
  "Mm-mm-mm, might let it go",
  "Oh, oh, oh, might let it go",
  "Mm-mm-mm, might let it go",
  "Oh, oh, oh, might let it go",

  "Baby, let me pull your dress down (Dress down)",
  "Kiss you from your neck down (Neck down)",
  `Have you screaming "Oh"`,
  "Baby, just let me pull your dress down (Dress down)",
  "Kiss you from your neck down (Neck down)",
  `Have you screaming "Oh," them sex sounds`,
];
